### ISSUE TITLE
Allow to stop connection process

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdGuardVPNForWindows#293]
### Problem Description

Sometimes the connection lasts a very long time and the process cannot be interrupted by the Disconnect button.

**Comment by adbuker** [comment]
Good news - starting from the nightly 6 (will be published tomorrow - on 16 March 2023) in order to invoke stopping the connecting process you can simply press `ctrl+C` hotkey. Of course it's a temporarily solution until the appropriate change will be implemented in the UI (honestly, it takes a bit more time to implement UI changes). Nevertheless, the duration of using such a workaround be no more than a couple of weeks
