### ISSUE TITLE
When installing Adgaurd VPN Windows have to disable bitdefender Anivirus

### ISSUE THREAD

**Issue by Batman2814** [AdguardTeam/AdGuardVPNForWindows#315]
When I was trying to install Adguard VPN for Windows stable version and also Adguard Adblocker stable version for Windows I had to disabled bitdefender security Antivirus in order to install it on my computer.

**Comment by mozartinio** [comment]
@Batman2814 Hello! I tried to reproduce it but everything works fine and successfully downloaded AdGuard Adblocker and AdGuard VPN. Is it always happening or only once?

**Comment by Batman2814** [comment]
when I tried to install Adguard VPN for windows stable one i got to the point where it was showing the status bar of adgaurd VPN and it will not load so that when i disabled bitdefender and it loading the full install page. but if its fine then next time I install the stable after I'm done testing the nightly then I will let you know if if worked.

**Comment by mozartinio** [comment]
@Batman2814 It is not fine and in order to resolve this issue we need you to do next steps please:
1. Select 'Run' command in Start menu or press (Win+R), then type in %tmp% and click on 'OK':
2. In the opened folder select all files starting with 'Adguard' and add them to archive (using WinRAR, for example):
3. Send this archive to AdGuard tech support (support@adguard.com)
https://kb.adguard.com/en/windows/solving-problems/installation-logs

**Comment by mozartinio** [comment]
@Batman2814 Any updates?

**Comment by Batman2814** [comment]
Been busy but I'm going to check to see if I'm able to download Adgaurd VPN with Bitdefender security enabled. I'll let u know if it works and if it does I will close the case.

**Comment by mozartinio** [comment]
@Batman2814 Got you. Waiting for result!

**Comment by Batman2814** [comment]
seem to work fine this time when installing Adguard VPN Public and nightly so I'm going to close this case.
