### ISSUE TITLE
AdguardVPN tryinig to connect to minorconvivialstructure.net

### ISSUE THREAD

**Issue by sangalaviral** [AdguardTeam/AdGuardVPNForWindows#526]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN version

2.1.2(1000)

### Operating mode

VPN

### Environment

```markdown
- OS:Windows 11
- Other network-level software:
```

### Issue Details

Steps to reproduce:
1. Open AdGuard VPN
2. Start Monitoring Internet traffic

### Expected Behavior

AdGuardVPN is trying to access api.minorconvivialstructure.net and auth.minorconvivialstructure.net

The domain was registered in last 30 days and there is no mention why this connection is being tried.

### Actual Behavior

Either provide an explanation to what data is being transmitted to this domain and why the regular domain not being used.

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by ameshkov** [comment]
@sangalaviral depending on the user network we may use alternative API and AUTH domains instead of the regular ones. This is a measure that are supposed to be used in the networks with aggressive censorship. There's a small chance that it'll be used in regular networks if for some reason AGVPN decides that something is wrong with the connection to regular API/AUTH domains.
