### ISSUE TITLE
Update button does not work

### ISSUE THREAD

**Issue by eduardoaddad** [AdguardTeam/AdGuardVPNForWindows#53]
In the last 3 versions, the update button has no action beyond the warning that a new version exists

To update I need to manually install the application

**Comment by Aydinv13** [comment]
Here we need you to collect logs too:
1. Collect the debug log: Settings- export logs
2. Remember the exact time when the issue was reproduced, we will need it to find the corresponding records in the log file.
3. Send the archive to devteam@adguard.com and mention this issue number in the subject (#53).

**Comment by eduardoaddad** [comment]
I will wait for the next update to be able to send the log in the email

**Comment by eduardoaddad** [comment]
Log sending by email

**Comment by Aydinv13** [comment]
@eduardoaddad has the problem gone?

**Comment by eduardoaddad** [comment]
for me this problem is no longer occurring

**Comment by Alex-302** [comment]
Still reproduced on my end. 1.0.216.0

**Comment by adbuker** [comment]
@Alex-302 , @eduardoaddad, could you please check in the latest nighlty

**Comment by Alex-302** [comment]
Works, as I remember.
