### ISSUE TITLE
In some cases the application does not start

### ISSUE THREAD

**Issue by eduardoaddad** [AdguardTeam/AdGuardVPNForWindows#54]
In some cases the application does not start and gets stuck on the loading screen

To solve this it is necessary to do a clean installation of the application again

**Comment by Aydinv13** [comment]
To troubleshoot this issue, we need to get the app logs.
Here's what we need you to do:
1. Collect the debug log as it's explained [here](https://kb.adguard.com/en/windows/solving-problems/adguard-logs).
2. Remember the exact time when the issue was reproduced, we will need it to find the corresponding records in the log file.
3. Send the archive to devteam@adguard.com and mention this issue number in the subject (#54).

**Comment by Aydinv13** [comment]
Closed due to no response. Reopen if needed
