### ISSUE TITLE
When using QUIC (expermental) is enabled connections start to fail.

### ISSUE THREAD

**Issue by Batman2814** [AdguardTeam/AdGuardVPNForWindows#557]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN version

2.1.10

### Operating mode

VPN

### Environment

```markdown
- OS: Windows 11, 22H2, build (10.0.22621)
- Other network-level software:
Bitdefender Total Security Anti-Virus Protection.
```

### Issue Details

Steps to reproduce:
1. Enable QUIC Experimental 
2. open your browser and use it. 
3. you will notice connections start to slow down and freeze connections until I disconnect the VPN.

### Expected Behavior

It should load connections all the time when the VPN is connected. 

### Actual Behavior

Slows connections, eventually leading to websites not loading when QUIC Experimental is enabled in AdGuard VPN. 

### Additional Information

For more additional information, the browser I use is Firefox.

**Comment by Batman2814** [comment]
Logs have been Sent just now.

**Comment by AlexandrPkhm** [comment]
Hi @Batman2814 

Your logs have been received. Also, could you please specify if the issue occurs with Bitdefender Anti-Virus protection turned off?

**Comment by Batman2814** [comment]
I'll Check and get back to you.

**Comment by AlexandrPkhm** [comment]
Hi @Batman2814 

Any news on the issue?

**Comment by Batman2814** [comment]
So, I did some testing and couldn't tell you if Bitdefender was the problem. It might be or might not be, but all I know is connections were failing when QUIC was enabled.

**Comment by AlexandrPkhm** [comment]
@Batman2814 

After checking the logs, we could not find any problems with the AdGuard VPN application. Therefore, we recommend that you try to add AdGuard VPN to Bitdefender antivirus exclusions to completely avoid any possible impact caused by antivirus software. 

We would also like to point out that the current QUIC implementation in AdGuard VPN is in an experimental stage and instability is expected. At the moment it is better to disable QUIC if you are looking for stable performance.
