### ISSUE TITLE
A few simple facilitation enhancement suggestions

### ISSUE THREAD

**Issue by RomenZero** [AdguardTeam/AdGuardVPNForWindows#566]
### Issue Details

Okay, sorry, I need to use translation software to discuss this issue in English

### Proposed solution

Sometimes we need to manually close AdGuard or AdGuard VPN, but currently there is no setting that allows us to directly close or connect them through keyboard combinations,
AdGuard VPN also did not follow AdGuard's example by adding a 30 second disconnection feature entry, which is a very convenient design, especially for some areas with strict censorship
When some sites are inaccessible or slow to access when logging into AdGuard VPN, it is often useful to add an exclusion item to them. However, not all sites are like this. There are still some sites that I can only access normally by temporarily closing AdGuard VPN. Therefore, can I try adding these sites to the exclusion list in the settings, which will automatically detect and silently disconnect and reconnect them, or push users to access the current website, Expert users can still make their own adjustments according to the current settings
AdGuard has a browser assistant to assist users in setting browser and website settings, but AdGuard VPN does not have such a magical tool. The settings in the AdGuard VPN browser extension cannot help AdGuard VPN for Windows fill out exclusion items. Like AdGuard's browser extension, the rules written in it only apply to the browser extension version and are not shared with the Windows version, So it is necessary to design an AdGuard VPN Browser Assistant similar to the AdGuard Browser Assistant to assist in filling out exclusion items and disconnecting the AdGuard VPN connection within 30 seconds
Many times, latency does not mean everything. During the process of using AdGuard VPN, we can easily feel that the connection in some areas is more stable. Therefore, we often return to these warm harbors when trying new nodes and experiencing poor experience. However, the main interface of AdGuard VPN does not give us the location to save the list of these nodes that we prefer, which is strange, In the context menu of the task tray, there is a simplified version of the history connection record, but of course, it is still more stable to have a dedicated favorites, right? They will not be accidentally refreshed and lost
When the network is unstable, the software frequently sends connection and disconnection messages, but we cannot turn it off. Some users need these strong prompts, but there are also many skilled users who do not need them. Experienced users have mastered the taskbar and only need to glance at the task tray - by marking it yellow or green, they know that they are disconnected or connected, and unnecessary notifications can make them very distressed
And, if you're interested, can you make a short animation of the ninja's lurking movements when connecting to AdGuard VPN for Windows? It would be even more interesting to randomly play from various hidden animations. Now suddenly hiding in the bushes like this is not cool at all
Trust has become increasingly expensive, but you are worth it. AdGuard's products have given me a full experience of the refreshing interface, and most of the time they have lived up to my expectations Of course, there are still advertisements that cannot be intercepted,
But of course, AdGuard will overcome difficulties in subsequent updates, and I trust

**Comment by AlexandrPkhm** [comment]
Hi @RomenZero 

We have analysed your suggestions and come to the following conclusions:

- Exiting AdGuard using hotkeys is not implemented to prevent accidental application closure and to ensure continuous protection. This precaution also applies to AdGuard VPN, where a hotkey exit could inadvertently expose the user's actual location and IP address.

- A 30-second disconnect option is not planned for AdGuard VPN due to the short timeframe for meaningful activity. However, a sudden disconnect could compromise the user's security. Similarly, the AdGuard VPN Browser Assistant is not prioritized because it doesn't have a specific functionality for which it could serve as a shortcut.

- Exclusions are already implemented in AdGuard VPN. Users can manually add websites or entire applications to exclusions and redirect their traffic away from the VPN tunnel.

- Additional ninja animations are not currently planned for implementation due to potential complexity and application performance issues.

However, we would like to let you know that the issue of unwanted connection notifications has been addressed by our development team and will be available in future releases. The favourite endpoint list is also planned for implementation, but we are unable to provide a timeframe for its release.
