### ISSUE TITLE
Missing strings at Crowdin from AdGuard VPN website

### ISSUE THREAD

**Issue by gork7777** [AdguardTeam/AdGuardVPNForWindows#577]
### Issue Details

The strings in the Support -> FAQ section (all tabs sections) on the AdGuard VPN website are missing and don't exist at Crowdin. These strings have not been added for a very long time. I wrote it here to take action, can you add these strings to be translated?

<details><summary>Screenshot 1:</summary>

![missing1](https://github.com/AdguardTeam/AdGuardVPNForWindows/assets/35523759/73a431f0-d23f-44b3-8594-f11b2b957f67)
</details>

<details><summary>Screenshot 2:</summary>

![missing2](https://github.com/AdguardTeam/AdGuardVPNForWindows/assets/35523759/527cf419-48fd-4dc1-91b4-334b52b14199)
</details>

<details><summary>Screenshot 3:</summary>

![missing3](https://github.com/AdguardTeam/AdGuardVPNForWindows/assets/35523759/303e5eed-7022-485e-aecb-d21db01da5a1)
</details>

**Comment by Aydinv13** [comment]
@gork7777 Thank you! Unfortunately, I have to close this issue because it doesn't have to with the desktop app.

**Comment by gork7777** [comment]
@el-termikael Could you take care of this issue?

**Comment by gork7777** [comment]
@el-termikael It's okay. I understand that you don't want to overload the contributors, maybe there could be a vote on this. It could also be that users look at this support section first instead of the Knowledge Base, because the FAQ doesn't contain detailed information and that's where users look first.

**Comment by el-termikael** [comment]
@gork7777 Hello,

We have discussed this issue and, unfortunately, we have to keep the Support section of the website in a private project.

The thing is that this section must be either 100% translated into a certain language or not translated at all. We appreciate the input of each contributor, but we realize that they can't guarantee us that 100%.

The reason for this is that there is a certain logic in the naming of string keys, a certain structure inherent in this section, so that we can build a tree of these web pages.

All this sounds quite complicated, but hopefully will give a better understanding of why we can't migrate the Support strings to AdGuard Websites.
