### ISSUE TITLE
Add configuration to block IPv6, WebRTC and DNS server

### ISSUE THREAD

**Issue by eduardoaddad** [AdguardTeam/AdGuardVPNForWindows#63]
Add configuration to block IPv6, WebRTC and DNS server

**Comment by adbuker** [comment]
@eduardoaddad , сould you please specify what do you exactly mean, do you want to add such blocking opportunities as the options to the AdGuardVpn? Blocking WebRTC feature is implemented in the AdGuard application, for blocking ipv6 you can tune your OS's firewall and for blocking particular DNS server you can add appropriate rules to the AdGuard also

**Comment by eduardoaddad** [comment]
Add Opportunities to Block WebRTC Without Relying on AdGurd Program

**Comment by adbuker** [comment]
@eduardoaddad , it's a duplicate functionality. If following such logic we should add any other stealth-mode options.

**Comment by olavinto** [comment]
> @eduardoaddad , it's a duplicate functionality. If following such logic we should add any other stealth-mode options.

I am against this and would instead deepen the integration between the applications so that AdGuard VPN would simply link with the settings of AdGuard and control those instead (for example). I see no benefit in duplicating these features and it would needlessly complicate and bloat the VPN application. Sure, then one would not need to use the AdGuard application alongside the VPN application but if one wants to block stuff and get more control over blocking and filtering anyway, I do not see why they wouldn't. It's not even that expensive to get a lifetime license to AdGuard, especially if one can afford a VPN subscription (I am obviously not including the free VPN service).

Even now there is overlap because both apps have DNS settings and neither really tells the user which application takes priority when it comes to DNS and this should be addressed somehow, at the very elast there should be a notification telling the user that the DNS configuration of the VPN application takes prority.

**Comment by adbuker** [comment]
@olavinto , AdGuard and AdGuardVPN have the different aims. The first one is needed to filter user's traffic whereas the second one - to provide anonymity. Both applications use DNS (obviously) and following the VPN app's DNS service priority we "duplicate" such logic in each ones. As for notification about such priority - it's useful suggestion, we'll work on it
