### ISSUE TITLE
Using Wintun Driver potentially causes a DPC_WATCHDOG_VIOLATION BSOD from a tcpip.sys error? Looking to reproduce.

### ISSUE THREAD

**Issue by TheD0ct0r101** [AdguardTeam/AdGuardVPNForWindows#641]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN version

2.2.4 (1271)

### Operating mode

VPN

### Environment

```markdown
- OS: Windows 10 Pro, 22H2, build 19045.4123
- Other network-level software: Adguard for Windows
```

### Issue Details

Steps to reproduce:
1. Enable Adguard VPN's Wintun driver
2. Wait around and/or perform usual tasks
3. Get BSOD

### Actual Behavior

I got a BSOD about an hour after enabling the Wintun driver functionality. After looking into the error and running the minidump through WinDbg, it seemed to point toward tcpip.sys, which is the network driver. But what makes this noteworthy to me is the fact that I have never received such a BSOD until soon after enabling the Wintun driver setting. If it's at all possible to try and re-create this issue then by all means.

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by TheD0ct0r101** [comment]
Updating to the Nightly build "2.3.0 nightly 20 (1333)" has only made it worse. Now instead of bluescreening, when using the Wintun driver my computer will instantly shutdown as if it had a power failure. This _exclusively_ occurs when using the Wintun setting and doesnt happen if I dont use it.

**Comment by AlexandrPkhm** [comment]
Hi @TheD0ct0r101 

To diagnose and troubleshoot this issue, we need to get the app logs. Here's what we need you to do:

1. Go to Settings → App settings → Logging level → **Record everything**;
2. Reproduce the problem and remember the exact time it was reproduced at. We will
need it to find the corresponding entries in the log file;
3. Open Support tab → **Export logs and system info**;
4. Send the archive to `devteam@adguard.com` and mention this issue number in the subject. Don't forget to include the time of reproduction.
5. Set the logging level back to **Record by default**.

Since this is a BSOD issue, we will also need a [memory dump](https://community.withsecure.com/en/kb/articles/29500-creating-a-memory-dump-file-after-getting-a-blue-screen-of-death-bsod) and Windows event log messages related to a BSOD. Please send these files along with the debug logs to `devteam@adguard.com`.

**Comment by AlexandrPkhm** [comment]
@TheD0ct0r101 

Could you please let us know if there are any news on the issue?
