### ISSUE TITLE
Add new languages (sv, slv, pl, id, uk) to the app

### ISSUE THREAD

**Issue by SeverAnna** [AdguardTeam/AdGuardVPNForWindows#650]
### Issue Details

Strings in Crowdin are 100% translated for the following languages:

- Swedish
- Slovenian
- Indonesian
- Polish
- Ukrainian

Would be cool to have these available in the app

**Comment by mahara** [comment]
Thanks for adding Indonesian language or "Bahasa Indonesia". The term "Bahasa Indonesia" should be used instead of just "Bahasa" in the language selection UI however. "Bahasa" means only "language" in English, which doesn't specify which language it is.

Please see the following references.
- https://www.quora.com/Why-do-Indonesians-call-their-language-Bahasa-Indonesia-when-the-proper-term-is-Bahasa-or-Bahasian-Isnt-that-redundant/answer/Naufal-Rizky-Rahardian-%D9%86%D9%88%D9%81%D9%84-%D8%B1%D8%B2%D9%82%D9%8A-%D8%B1%D8%A7%D9%87%D8%B1%D8%AF%D9%8A%D8%A7%D9%86
- https://www.quora.com/Why-is-the-English-equivalent-of-Bahasa-Indonesia-bahasa-or-worse-Bahasian-instead-of-the-Indonesian-language
