### ISSUE TITLE
AdguardVPN doesn't installing on windows 11

### ISSUE THREAD

**Issue by KriwkA** [AdguardTeam/AdGuardVPNForWindows#692]
### Please answer the following questions for yourself before submitting an issue.

- [X] I checked the [knowledge base](https://adguard-vpn.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN version

actual installer

### Environment

```markdown
- OS: Windows 11 Pro, 23H2 (OS build 22631.3737)
- Other network-level software:
```

### Which DNS server do you use?

Default

### Use Wintun

- [ ] yes, I do

### Issue Details

Steps to reproduce:
1. Download installer from https://adguard-vpn.com/download.html?auto=1&os=windows
2. Run installer
3. nothing happend

### Actual Behavior

AdguardVPN doesn't installing
Log:
[AdguardVPN_20240614203916.log](https://github.com/user-attachments/files/15841721/AdguardVPN_20240614203916.log)

### Screenshots

<details><summary>Screenshot 1</summary>

</details>

**Comment by KolbasovAnton** [comment]
@KriwkA Greetings!

1. You can always download latest release and beta versions from our "[Releases](https://github.com/AdguardTeam/AdGuardVPNForWindows/releases)" section of GitHub.
2. As I can see from logs, your issue relates to TLS protocols. You can try to fix it this way:
 - Run **_regedit_** as Administrator.
 - Go to **_HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\.NETFramework\v4.0.30319_**
 - Click RMB on the field with entries and select **_Create -> DWORD_**.
 - As a name of new entry enter **_SchUseStrongCrypto_**
 - After creation of entry click on it with RMB and select **_Edit_**. In **_Value_** field enter the number **_1_**. Press **_OK_** button.
 - Go to **_HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\.NETFramework\v4.0.30319_** and perform the same steps, as above - create **_DWORD_** entry and set its **_Value_** as **_1_**.
 - Close the regisrty, reboot Your PC and try to run AG VPN installer once more.
 - If it doesn't work, try the exact same actions, but instead of **_DWORD_** entries, make **_QWORD_** entries in both folders (delete previously created DWORD entries before it).

Please, let us know, if it works or not.

**Comment by zubrRB** [comment]
@KriwkA Tell me, do you have the KB5039212 update installed on your system? https://github.com/AdguardTeam/AdGuardVPNForWindows/issues/698#issuecomment-2178316632

**Comment by KolbasovAnton** [comment]
@KriwkA Any news? Did You manage to install the app?
