### ISSUE TITLE
Low speed on Yotube without using of QUIC

### ISSUE THREAD

**Issue by shamarin** [AdguardTeam/AdGuardVPNForWindows#734]
### Please answer the following questions for yourself before submitting an issue.

- [X] I checked the [knowledge base](https://adguard-vpn.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard VPN version

2.4 nightly 13

### Environment

```markdown
- OS:Win11 22635.4145 x64 and Win 11 24H2 26100 x64
- Other network-level software:
```

### Which DNS server do you use?

Default

### Use Wintun

- [X] yes, I do

### Issue Details

Steps to reproduce:
1. Check that QUIC is disabled in Adguard VPN settings
2. Connect to any fast location
3. Go to Youtube in browser and open any full HD or 4k video

### Expected Behavior

Speed should be about 100 Mbits for 100 Mbits ISP provider tariff

### Actual Behavior

Actual speed is about 10 Mbits maximum and always such resolution videos get stucked to buffering.

### Screenshots

<details><summary>Screenshot 1</summary>

</details>

### Additional Information

If to check Youtube statistics for admins it's showing that connection speed is about 7-10 Mbits. With enabling of the QUIC protocol speed is fast (about 70-90 Mbits). At that moment no other networking traffic is used in system, I mean no torrent client is working or another apps that can use traffic. Also this happens with Wintun enabled and without it. Tested on two different machines with different ISP providers. The same situation happens on both of them. Also it must be taken in to consideration that Youtube is blocked in Russia. On other web resources speed is fast with the same location connected and without using of the QUIC protocol.

**Comment by shamarin** [comment]
Checked today on my third machine with 300 Mbits plan from ISP, just the same on Youtube.

**Comment by AlexandrPkhm** [comment]
Hi @shamarin 

Unfortunately, we were unable to reproduce this issue on our end. In order to diagnose and troubleshoot this issue, we need to get your application logs.

Here's what we need you to do:

1. Go to *Settings → App settings → Logging level → Record everything*.
2. Reproduce the problem, then remember the exact time it happened.
3. Open *Support tab → Export logs and system info*.
4. Send the archive to [qa@adguard.com](mailto:qa@adguard.com):
		- include `[windows]` keyword and `ISSUE_NUMBER` in the subject of your email
		- specify the exact time when the issue occurred

**Comment by shamarin** [comment]
> Hi @shamarin
> 
> Unfortunately, we were unable to reproduce this issue on our end. In order to diagnose and troubleshoot this issue, we need to get your application logs.
> 
> Here's what we need you to do:
> 
>     1. Go to _Settings → App settings → Logging level → Record everything_.
> 
>     2. Reproduce the problem, then remember the exact time it happened.
> 
>     3. Open _Support tab → Export logs and system info_.
> 
>     4. Send the archive to [qa@adguard.com](mailto:qa@adguard.com):
>        - include `[windows]` keyword and `ISSUE_NUMBER` in the subject of your email
>        - specify the exact time when the issue occurred

Sended.

**Comment by AlexandrPkhm** [comment]
@shamarin Our development team has reviewed the log files you provided and would like to confirm that this behaviour is expected. QUIC as a protocol, even though it is an experimental implementation, should be faster because it uses UDP. Also, your network environment and various other factors can cause the difference in speed.

Unfortunately, we are not planning on working on this issue.

**Comment by shamarin** [comment]
> @shamarin Our development team has reviewed the log files you provided and would like to confirm that this behaviour is expected. QUIC as a protocol, even though it is an experimental implementation, should be faster because it uses UDP. Also, your network environment and various other factors can cause the difference in speed.
> 
> Unfortunately, we are not planning on working on this issue.

Not yet understand you. What's wrong with my network environment??? So I need to use QUIC allways?
