### ISSUE TITLE
Add website list synchronization between devices

### ISSUE THREAD

**Issue by lansman** [AdguardTeam/AdGuardVPNForWindows#773]
### Issue Details

There are so many sites are being blocked every day. I have several devices (PC, laptops, phones) and have to add each site to every device, this is very tedious.

### Proposed solution

Add list synchronization feature please. You can implement it in the fast and simple way, just over local network, so you don't have to implement API and prepare storage on your servers.

We need this on Windows, Mac, Android clients.

**Comment by AlexandrPkhm** [comment]
@lansman Hello! 

Unfortunately, we have no plans to add this feature at this time. However, we would like to remind you that you can export your exclusions on one device and use that exported file on any other device. Because the exclusions are exported in .txt files, these files are cross-platform.
